---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
    # Should be changed to 1.0 when supported https://github.com/codeclimate/codeclimate-rubocop/issues/262
    channel: rubocop-0-92
    config:
      file: .rubocop_cc.yml

ratings:
  paths:
  - "**.rb"
exclude_paths:
- spec/
- lib/skylight/vendor/
